swagger: "2.0"

info:
  title: "GroceryBLISS API"
  version: "1.0"

basePath: /api/v1

consumes:
  - application/json
produces:
  - application/json

paths:
  /login:
    post:
      summary: Login using github
      description: Login using a github authorization code
      operationId: controllers.login
      parameters:
      - name: body
        in: body
        description: Login body
        required: true
        schema:
          type: object
          required:
            - code
          properties:
            code:
              type: string
              description: Code returned from github authentication
      responses:
        200:
          description: Login successful and user info
          schema:
            type: object
            properties:
              user_id:
                type: string
                description: Id of the user on github
              username:
                type: string
                description: Username on github
              avatar_url:
                type: string
                description: Users avatar image on github
              access_token:
                type: string
                description: Access token to use with the github api
        401:
          description: Authentication failure

  /logout:
    post:
      summary: Logout
      description: Remove the existing session
      operationId: controllers.logout
      responses:
        200:
          description: Logout successful
